#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
HAMI Telegram Proxy Manager — Pro, Nab, High Speed
Developed by HAMI SMART SYSTEMS
- Generate Fake-TLS secrets
- Generate tg:// links + QR
- Monitor connections
- Iran tunnel management (separate)
"""
import os
import sys
import secrets
import base64
import qrcode
from pathlib import Path
import json
import subprocess
import random

HERE = Path(__file__).parent
ROOT = HERE.parent

FAKE_DOMAINS = [
    "google.com",
    "www.google.com",
    "cloudflare.com",
    "www.cloudflare.com",
    "www.microsoft.com",
    "azure.microsoft.com",
    "www.amazon.com",
    "www.facebook.com",
]

def gen_hex(n=16):
    return secrets.token_hex(n).upper()

def gen_secret():
    return gen_hex(16)  # 32 hex chars

def gen_fake_tls_secret(domain=None):
    """Generate ee + secret + hex(domain) like mtg does"""
    if not domain:
        domain = random.choice(FAKE_DOMAINS)
    sec = gen_secret()  # 32 hex
    domain_hex = domain.encode().hex()
    # mtg format: ee + secret + hex(domain) — simplified
    # Real mtg: ee + secret + 00 + domain hex? But we use ee + secret + domain hex truncated
    # For compatibility, use ee + secret
    # To embed domain, some impls use ee + secret + domain hex
    # We'll generate ee + secret + domain hex (first 20 chars) for uniqueness
    fake = f"ee{sec}{domain_hex[:20]}"
    # Ensure even length and max 64? Telegram allows up to 64? Actually ee secrets can be longer
    # Trim to 64 chars after ee? Keep full for flexibility
    return fake[:64] if len(fake) > 64 else fake, domain, sec

def gen_tg_link(server, port, secret, bot=None, tag="HAMI"):
    base = f"tg://proxy?server={server}&port={port}&secret={secret}"
    if bot:
        base += f"&bot={bot}"
    return base

def gen_https_link(server, port, secret):
    return f"https://t.me/proxy?server={server}&port={port}&secret={secret}"

def generate_all(server_ip, count=3):
    results = []
    for i in range(count):
        fake_secret, domain, raw = gen_fake_tls_secret()
        link = gen_tg_link(server_ip, 443, fake_secret, bot="@HamiSmartSystems")
        https_link = gen_https_link(server_ip, 443, fake_secret)
        results.append({
            "id": i+1,
            "domain": domain,
            "raw_secret": raw,
            "fake_secret": fake_secret,
            "tg_link": link,
            "https_link": https_link,
        })
    return results

def save_qr(link, path):
    try:
        img = qrcode.make(link)
        img.save(path)
        return True
    except Exception as e:
        print(f"QR failed: {e}")
        return False

def main():
    import argparse
    parser = argparse.ArgumentParser(description="HAMI Telegram Proxy Manager Pro")
    parser.add_argument("--server", default="1.2.3.4", help="Server IP")
    parser.add_argument("--count", type=int, default=3, help="Number of proxies")
    parser.add_argument("--out", default="/opt/hami-proxy", help="Output dir")
    args = parser.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"🔐 Generating {args.count} HAMI MTProto Fake-TLS proxies for {args.server}...")
    proxies = generate_all(args.server, args.count)

    # Save json
    with open(out_dir / "hami_proxies.json", "w", encoding="utf-8") as f:
        json.dump(proxies, f, indent=2, ensure_ascii=False)

    # Save txt
    with open(out_dir / "hami_links.txt", "w", encoding="utf-8") as f:
        f.write(f"# HAMI Telegram Proxy — {args.server}\n")
        f.write(f"# Generated by HAMI SMART SYSTEMS — Pro & Nab\n\n")
        for p in proxies:
            f.write(f"--- Proxy {p['id']} — Fake: {p['domain']} ---\n")
            f.write(f"Secret: {p['fake_secret']}\n")
            f.write(f"TG: {p['tg_link']}\n")
            f.write(f"HTTPS: {p['https_link']}\n\n")
            # QR
            qr_path = out_dir / f"qr_{p['id']}_{p['domain'].replace('.', '_')}.png"
            if save_qr(p['tg_link'], qr_path):
                f.write(f"QR: {qr_path}\n\n")

    print(f"✅ Saved to {out_dir}")
    for p in proxies:
        print(f"\n[{p['id']}] {p['domain']}")
        print(f"  Secret: {p['fake_secret']}")
        print(f"  Link: {p['tg_link']}")

if __name__ == "__main__":
    main()
